services:
  highlighter-demo.api:
    image: keyy1315/highlighter-demo.api:latest
    container_name: highlighter-demo.api
    ports:
    - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/lol
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - highlighter-network
  highlighter-fast.api:
    image: keyy1315/highlighter-fast.api:latest
    container_name: highlighter-fast.api
    ports:
      - "8082:8082"
    command: uvicorn app:app --host 0.0.0.0 --port 8082
    networks:
      - highlighter-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - highlighter-vol-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-time-zone=Asia/Seoul
      --default-authentication-plugin=mysql_native_password
    networks:
      - highlighter-network
    restart: always
volumes:
  highlighter-vol-db: {}
networks:
  highlighter-network:
    driver: bridge

